[package]
name = "ker"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
